name: Build vale-style-JTI release
on: push
permissions:
  contents: write
jobs:
  build-style:
    name: Build style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout style
      uses: actions/checkout@v3
    - name: Setup ENV
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "RELEASE_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "REPO_NAME=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
        echo "REPO_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" >> $GITHUB_ENV
    - name: Make ZIP
      run: zip -r JTI JTI
    - name: Create release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "JTI.zip"
        allowUpdates: true
        generateReleaseNotes: true
        tag: latest
        token: ${{ secrets.GITHUB_TOKEN }}
